services:
  postgres:
    image: postgres:18-alpine3.23
    environment:
      POSTGRES_USER: flappy
      POSTGRES_PASSWORD: flappy
      POSTGRES_DB: flappydb
    volumes:
      - flappy_pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flappy -d flappydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_net

  backend:
    environment:
      - STORAGE_TYPE=postgres
      - DATABASE_DSN=postgresql://flappy:flappy@postgres:5432/flappydb
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend_net

volumes:
  flappy_pgdata:

networks:
  backend_net:
